=== osandum/gambol-docs/src/main/resources/gambol.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           targetNamespace="http://sandum.net/namespaces/gambol"
           xmlns:g="http://sandum.net/namespaces/gambol"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           jaxb:version="2.1"
           xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
           jaxb:extensionBindingPrefixes="xjc">

    <xs:annotation>
        <xs:appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="gambol.xml"/>
            </jaxb:schemaBindings>
            
            <jaxb:bindings>
                <jaxb:globalBindings >
                    <xjc:javaType 
                        name="java.util.Date"
                        xmlType="xs:dateTime"
                        adapter="net.sandum.xml.XmlDateTimeAdapter" />
                </jaxb:globalBindings>
            </jaxb:bindings>            
        </xs:appinfo>
    </xs:annotation>

    <xs:element name="gambol">
        <xs:complexType>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="section" minOccurs="0" maxOccurs="unbounded" type="g:Section"/>
                </xs:sequence>
                <xs:element name="tournament">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="fixture" minOccurs="0" maxOccurs="unbounded" type="g:Fixture"/>
                        </xs:sequence>                    
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="season" type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Section">
        <xs:sequence>
            <xs:element name="title" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="tournament" minOccurs="0" maxOccurs="unbounded" type="g:Tournament"/>
        </xs:sequence>
 
        <xs:attribute name="id" type="xs:int" />
    </xs:complexType>

    <xs:complexType name="Tournament">
        <xs:sequence>
            <xs:element name="title" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="fixture" minOccurs="0" maxOccurs="unbounded" type="g:Fixture"/>
        </xs:sequence>
 
        <xs:attribute name="id" type="xs:int" />
    </xs:complexType>

    <xs:complexType name="Fixture">
        <xs:sequence>
            <xs:element name="diu-match-id" minOccurs="0" maxOccurs="1" type="xs:string"/>
            <xs:element name="side" minOccurs="1" maxOccurs="unbounded" type="g:Side" />
            
            <xs:element name="start-time" minOccurs="1" maxOccurs="1" type="xs:dateTime"/>
            <xs:element name="result" minOccurs="0" maxOccurs="1">
            </xs:element>
        </xs:sequence>
 
        <xs:attribute name="id" type="xs:int" />
    </xs:complexType>

    <xs:complexType name="Side">
        <xs:sequence>
            <xs:element name="score" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
 
        <xs:attribute name="id" type="xs:int" />
        <xs:attribute name="role" type="xs:string" />
    </xs:complexType>

</xs:schema>

=== osandum/gambol-docs/src/test/resources/sample/tournaments-2013_14.xml
<?xml version="1.0" encoding="UTF-8"?>

<gambol xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://sandum.net/namespaces/gambol" 
        season="2013/2014" 
        xsi:schemaLocation="http://sandum.net/namespaces/gambol file:/Users/osa/KSF/diu-rip/src/main/xsd/gambol.xsd">
    <section id="0">
        <title>Turneringer, DIU</title>
        <tournament id="952">
            <title>Reebok Camp + Breddesamling</title>
        </tournament>
        <tournament id="983">
            <title>U20 - Vest</title>
        </tournament>
        <tournament id="984">
            <title>U20 - Øst</title>
        </tournament>
        <tournament id="985">
            <title>1. Division</title>
        </tournament>
        <tournament id="986">
            <title>Metal Ligaen</title>
        </tournament>
        <tournament id="987">
            <title>U17 Puljeturnering A</title>
        </tournament>
        <tournament id="988">
            <title>U17 Puljeturnering B</title>
        </tournament>
        <tournament id="989">
            <title>U15 Puljeturnering A</title>
        </tournament>
        <tournament id="990">
            <title>U15 Puljeturnering B</title>
        </tournament>
        <tournament id="993">
            <title>U18 Landskampe</title>
        </tournament>
        <tournament id="994">
            <title>U20 Landskampe</title>
        </tournament>
        <tournament id="995">
            <title>Metal Cup</title>
        </tournament>
        <tournament id="1001">
            <title>Kvindernes puljeturnering</title>
        </tournament>
        <tournament id="1006">
            <title>Kvindelandsholdet</title>
        </tournament>
        <tournament id="1007">
            <title>U13.2 Puljeturnering, december</title>
        </tournament>
        <tournament id="1009">
            <title>U13.1 Puljeturnering</title>
        </tournament>
        <tournament id="1013">
            <title>LM for U15.2</title>
        </tournament>
        <tournament id="1014">
            <title>LM for U13.2</title>
        </tournament>
        <tournament id="1022">
            <title>U20 DM-Kval Pulje B - Øst</title>
        </tournament>
        <tournament id="1023">
            <title>U17 DM Kvalifikation</title>
        </tournament>
        <tournament id="1024">
            <title>DM for U17</title>
        </tournament>
        <tournament id="1025">
            <title>DM for U15</title>
        </tournament>
        <tournament id="1026">
            <title>DM for U13</title>
        </tournament>
        <tournament id="1027">
            <title>SM for U13</title>
        </tournament>
        <tournament id="1028">
            <title>JM for U13</title>
        </tournament>
        <tournament id="1029">
            <title>DM for U20</title>
        </tournament>
        <tournament id="1030">
            <title>Kvindernes DM Kval</title>
        </tournament>
        <tournament id="1031">
            <title>Kvindernes DM Finaler</title>
        </tournament>
        <tournament id="1032">
            <title>U20 DM-Kval Pulje A</title>
        </tournament>
        <tournament id="1035">
            <title>1. division play-off</title>
        </tournament>
        <tournament id="1037">
            <title>Metal Ligaen, kvartfinaler</title>
        </tournament>
        <tournament id="1038">
            <title>Metal Ligaen, semifinaler</title>
        </tournament>
        <tournament id="1039">
            <title>Metal Ligaen, finaler</title>
        </tournament>
        <tournament id="1040">
            <title>Metal Ligaen, bronzekampe</title>
        </tournament>
    </section>
    <section id="1">
        <title>Turneringer, Øst</title>
        <tournament id="997">
            <title>Løve cup øst</title>
        </tournament>
        <tournament id="1015">
            <title>Play off U 17 gruppe 1</title>
        </tournament>
        <tournament id="1016">
            <title>Play off U 17 gruppe 2</title>
        </tournament>
        <tournament id="1033">
            <title>Play off U 15 gruppe 1</title>
        </tournament>
        <tournament id="1034">
            <title>Play off U 15 gruppe 2</title>
        </tournament>
        <tournament id="968">
            <title>U 17 øst grundspil</title>
        </tournament>
        <tournament id="969">
            <title>U 15 øst grundspil 1</title>
        </tournament>
        <tournament id="970">
            <title>U 13 øst udd</title>
        </tournament>
        <tournament id="976">
            <title>U 15 .2 øst</title>
        </tournament>
        <tournament id="971">
            <title>u 13 øst point</title>
        </tournament>
        <tournament id="975">
            <title>U 13.2 øst</title>
        </tournament>
        <tournament id="973">
            <title>U 11 øst</title>
        </tournament>
        <tournament id="974">
            <title>U 11.2 øst</title>
        </tournament>
        <tournament id="972">
            <title>Kvinder øst</title>
        </tournament>
        <tournament id="978">
            <title>U 9 Hvid øst</title>
        </tournament>
        <tournament id="977">
            <title>U 9 Rød øst</title>
        </tournament>
        <tournament id="982">
            <title>2 div. Øst</title>
        </tournament>
        <tournament id="979">
            <title>Old Boys 1 øst</title>
        </tournament>
        <tournament id="991">
            <title>Old Boys 2 øst</title>
        </tournament>
        <tournament id="981">
            <title>Old Boys 3 øst</title>
        </tournament>
    </section>
    <section id="2">
        <title>Turneringer, Vest</title>
        <tournament id="953">
            <title>U 11 vest</title>
        </tournament>
        <tournament id="954">
            <title>U 11.2 vest</title>
        </tournament>
        <tournament id="955">
            <title>U 13 udd. vest</title>
        </tournament>
        <tournament id="956">
            <title>U 13.2 vest</title>
        </tournament>
        <tournament id="957">
            <title>U 15 vest</title>
        </tournament>
        <tournament id="958">
            <title>U 15.2 vest</title>
        </tournament>
        <tournament id="959">
            <title>U 17 vest</title>
        </tournament>
        <tournament id="960">
            <title>U 17.2 vest</title>
        </tournament>
        <tournament id="961">
            <title>Kvinder vest</title>
        </tournament>
        <tournament id="962">
            <title>Division A - 2. div.</title>
        </tournament>
        <tournament id="963">
            <title>Division B</title>
        </tournament>
        <tournament id="964">
            <title>U 7 vest</title>
        </tournament>
        <tournament id="965">
            <title>U 9 vest</title>
        </tournament>
        <tournament id="966">
            <title>U 13 point vest</title>
        </tournament>
        <tournament id="967">
            <title>2 div.</title>
        </tournament>
        <tournament id="1017">
            <title>Play off U 17 gruppe 1, vest</title>
        </tournament>
        <tournament id="1018">
            <title>Play off U 17 gruppe 2, vest</title>
        </tournament>
        <tournament id="1019">
            <title>Play off U 15 gruppe 1, vest</title>
        </tournament>
        <tournament id="1020">
            <title>Play off U 15 gruppe 2, vest</title>
        </tournament>
    </section>
    <section id="3">
        <title>Turneringer, Øvrige</title>
        <tournament id="950">
            <title>Træningskampe Liga 2013/2014</title>
        </tournament>
        <tournament id="951">
            <title>Træningskampe øvrige 2013/2014</title>
        </tournament>
        <tournament id="996">
            <title>Czech Hockey Games</title>
        </tournament>
        <tournament id="998">
            <title>Løve Cup</title>
        </tournament>
        <tournament id="1000">
            <title>Testkampe</title>
        </tournament>
        <tournament id="1002">
            <title>Skåne U18.2</title>
        </tournament>
        <tournament id="1003">
            <title>Skåne U15.1</title>
        </tournament>
        <tournament id="1004">
            <title>Skåne U13.1</title>
        </tournament>
        <tournament id="1005">
            <title>Skåne U14.1</title>
        </tournament>
        <tournament id="1008">
            <title>Continental Cup Group E</title>
        </tournament>
        <tournament id="1010">
            <title>DanHostel Cup 2013</title>
        </tournament>
        <tournament id="1011">
            <title>DanHostel Cup 2013 - Semifinaler</title>
        </tournament>
        <tournament id="1012">
            <title>DanHostel Cup 2013 - Finaler</title>
        </tournament>
        <tournament id="1021">
            <title>Olympic Winter Games</title>
        </tournament>
        <tournament id="1036">
            <title>U 11 - Cup Aalborg</title>
        </tournament>
    </section>
</gambol>
